project_id = "jhbafgzfphiizpuoqksj"

[functions.mercadopago-webhook]
verify_jwt = false

[functions.play-scratch-card]
verify_jwt = true

[functions.suitpay-request-qrcode]
verify_jwt = false

[functions.suitpay-webhook]
verify_jwt = false

[functions.affiliate-commission-job]
verify_jwt = false

[functions.process-attribution]
verify_jwt = false
