// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhbafgzfphiizpuoqksj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoYmFmZ3pmcGhpaXpwdW9xa3NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MzE2NTksImV4cCI6MjA2NzAwNzY1OX0.u-S7hecuACaoVIdtApGxKTQFwsnqv1PVor47Pnfm_aM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});